from subprocess import Popen
from datamodels.camera import OpenFaceDataPoint
from datamodels.skeletal import SkeletalNodeCollection
import os
import shutil
import json
import time


class OpenPoseInstance:

    """
    This class will run the OpenPose binaries as a seperate process asynchronsly (non-blocking) and handle the datafiles that the program will generate.
    """

    process = None
    out_dir = "output_json/"

    file = None
    current_frame = 0
    current_data = SkeletalNodeCollection([])

    def __init__(self):
        self.clearOutputDirectory()

    def clearOutputDirectory(self):
        """
        Clear the previous output directory so that the timestamps for the new data will be correct (as the data itself does not have timestamps)
        """
        try:
            shutil.rmtree("./devices/openpose/bin/" + self.out_dir)
        except:
            pass

    def startProcess(self):
        """
        Start the program process by running the appropriate command line commands (This requires windows OS). Look at the OpenPoce documentation for more details of the arguments used.
        """
        try:
            self.process = Popen("bin\OpenPoseDemo.exe" +
                                 " --net_resolution -1x80" +
                                 " --tracking 1" +
                                 " --number_people_max 1" +
                                 " --process_real_time" +
                                 " --write_json " + self.out_dir +
                                 " --keypoint_scale 4",
                                 cwd=os.getcwd() + "\devices\openpose\\bin",
                                 shell=True)
        except FileNotFoundError:
            self.process = None
            print(
                "Couldn't find the OpenPose binaries, make sure they are installed correctly.")

    def terminateProcess(self):
        """
        Terminates the current process running.
        """
        if self.process:
            self.process.terminate()

    def readNextData(self):
        """
        Read the new unread data that has been generated by the process.
        Here every new frame will have its own json_file, but with a id name.
        """
        try:
            while True:
                self.file = open(
                    "./devices/openpose/bin/" + self.out_dir + self.getCurrentFileName(),
                )
                data = json.load(self.file)
                keypoints = data["people"][0]["pose_keypoints_2d"]
                dataRows = self.keypointsToDataRows(keypoints)
                self.current_data = SkeletalNodeCollection(dataRows)
                self.current_frame += 1
                self.file.close()
        except (FileNotFoundError, json.decoder.JSONDecodeError):
            pass

    def getCurrentFileName(self):
        """
            following format for frame 0: "000000000000_keypoints.json"
            following format for frame 1: "000000000001_keypoints.json"
            etc.
        """
        return str(self.current_frame).zfill(12) + "_keypoints.json"

    def keypointsToDataRows(self, keypoints):
        dataRows = []
        for i in range(0, len(keypoints), 3):
            jointType = i / 3
            x = keypoints[i + 0]
            y = keypoints[i + 1]
            z = 0
            c = keypoints[i + 2]
            t = time.time()
            dataRows.append([jointType, x, y, z, t])
        return dataRows

    def getCurrentData(self):
        """
        Read the next data and then return all the current data before it is cleared.
        """
        self.readNextData()
        return self.current_data

    def clearCurrentData(self):
        """
        Clear the current data
        """
        self.current_data = SkeletalNodeCollection([])
